### ISSUE TITLE
Hitting errors trying to launch

### ISSUE THREAD

**Issue by unchaoss** [romka/fruhling#4]
Hi, I'm new to Hugo and I got the Ananke script from the Quickstart to work then I tried Frhuling. My set up is

cbdasg@cbserver:~/Projects/quickstart$ ls themes/fruhling/
assets  exampleSite  i18n  images  layouts  LICENSE  README.md  static  theme.toml
cbdasg@cbserver:~/Projects/quickstart$ tail config.toml 
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = 'fruhling'
cbdasg@cbserver:~/Projects/quickstart$ 

When I launch hugo server I get errors as in the attached log. 

[fruhling-launch.log](https://github.com/user-attachments/files/17851098/fruhling-launch.log)

In case the log does not come through, here are the first few lines

Watching for changes in /home/cbdasg/Projects/quickstart/{archetypes,content,data,layouts,static,themes}
Watching for config changes in /home/cbdasg/Projects/quickstart/config.toml
Start building sites …
hugo v0.139.0-dacef0df92a9a20072b4eaa42003e1a63ace8f41+extended linux/amd64 BuildDate=2024-11-18T16:17:45Z VendorInfo=gohugoio

ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Implement taxonomy 'social' or use .Site.Params.Social instead.
ERROR render of "404" failed: "/home/cbdasg/Projects/quickstart/themes/fruhling/layouts/404.html:2:4": execute of template failed: template: 404.html:2:4: executing "photomosaic" at <partial "partials/shared/photomosaic.html" .>: error calling partial: "/home/cbdasg/Projects/quickstart/themes/fruhling/layouts/partials/shared/photomosaic.html:17:8": execute of template failed: template: partials/shared/photomosaic.html:17:8: executing "partials/shared/photomosaic.html" at <partialCached "partials/shared/photomosaic-impl.html" . $cacheId>: error calling partialCached: "/home/cbdasg/Projects/quickstart/themes/fruhling/layouts/partials/shared/photomosaic-impl.html:1:29": execute of template failed: template: partials/shared/photomosaic-impl.html:1:29: executing "partials/shared/photomosaic-impl.html" at <partialCached "partials/shared/photomosaic-data.html" .>: error calling partialCached: "/home/cbdasg/Projects/quickstart/themes/fruhling/layouts/partials/shared/photomosaic-data.html:6:10": execute of template failed: template: partials/shared/photomosaic-data.html:6:10: executing "partials/shared/photomosaic-data.html" at <readDir "/content/gallery">: error calling readDir: failed to read directory "/content/gallery": open /home/cbdasg/Projects/quickstart/content/gallery: no such file or directory

**Comment by romka** [comment]
Hi [unchaoss](https://github.com/unchaoss), thank you for your report.

> ERROR deprecated: .Site.Social was deprecated in Hugo v0.124.0 and will be removed in Hugo 0.140.0. Implement taxonomy 'social' or use .Site.Params.Social instead.

Ok, this isn't an error at this moment, but'll fix this.

> content/gallery">: error calling readDir: failed to read directory "/content/gallery": open /home/cbdasg/Projects/quickstart/content/gallery: no such file or directory

Yeah, the photomosaic header expects you have at least one gallery to take photos from. There is no reason to use fruhling theme without photogalleries, since it's supposed that photos are the main content type for the blog which uses this theme. At this moment, you can fix this issue by adding at least one gallery. I'll add a check for galleries existanse soon.
